theme: jekyll-theme-minimal
title: Furiganizer
description: Google Docs add-on that adds furigana to Japanese text
lang: en

# Google Site Verification
google_site_verification: UozVvtsiKqHw5FyqFYWTQNT-fCix2tY4QA0LeJFkmCA

# Files not to publish
exclude:
  - PUBLISHING.md
  - Code.gs
  - appsscript.json
